export const data_tempat_ppl = [
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
    {
        id: 1,
        name: "PPL Matematika MAN 3 Aceh Besar",
        quota: 12,
        terisi: 9,
        lokasi: "Indrapuri, Aceh Besar",
        IPK: 3.4,
    },
];

export const data_prodi = [
    { label: "Pendidikan Agama Islam", id: "1" },
    { label: "Pendidikan Bahasa Arab", id: "2" },
    { label: "Pendidikan Bahasa Inggris", id: "3" },
    { label: "Pendidikan Matematika", id: "4" },
    { label: "Manajemen Pendidikan Islam", id: "5" },
    { label: "Pendidikan Kimia", id: "6" },
    { label: "Pendidikan Fisika", id: "7" },
    { label: "Pendidikan Biologi", id: "8" },
    { label: "Pendidikan Guru Madrasah Ibtidaiyah", id: "9" },
    { label: "Pendidikan Islam Anak Usia Dini", id: "10" },
    { label: "Pendidikan Teknik Elektro", id: "11" },
    { label: "Pendidikan Teknologi Informasi", id: "12" },
    { label: "Bimbingan Konseling", id: "13" },
];

export const data_nilai = [
    { label: "A", id: "1" },
    { label: "A-", id: "2" },
    { label: "B+", id: "3" },
    { label: "B", id: "4" },
    { label: "B-", id: "5" },
    { label: "C+", id: "6" },
    { label: "C", id: "7" },
];
